### ISSUE TITLE
make: *** No rule to make target 'bytestream.o', needed by 'ppm2pwg'.  Stop.

### ISSUE THREAD

**Issue by philkunz** [attah/ppm2pwg#13]
Super interesting project.

I'm coming from TypeScript world... So I don't have much experience with make.

I'm getting 

```
make: *** No rule to make target 'bytestream.o', needed by 'ppm2pwg'.  Stop.
```
upon running make. Any idea what it means? :)

**Comment by attah** [comment]
Not a great error indeed... But i assume you didn't clone recursively i.e. did not get the submodule updated.

**Comment by attah** [comment]
@philkunz Did you get it working?

**Comment by talwrii** [comment]
For the uninitiated this means running `git submodule init` and `git submodule update`
