### ISSUE TITLE
make: *** No rule to make target 'install'.  Stop.

### ISSUE THREAD

**Issue by milahu** [attah/ppm2pwg#26]
the missing `install` rule makes it 1% harder to package `ppm2pwg`

see also [ppm2pwg-git/PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ppm2pwg-git)

```sh
package() {
    cd "${srcdir}/ppm2pwg"

    utils=(
        ppm2pwg
        pwg2ppm
        pdf2printable
        baselinify
        ippposter
    )

    for util in "${utils[@]}"; do
        install -D -m755 "$util" "${pkgdir}/usr/bin/$util"
    done
}
```

**Comment by attah** [comment]
The thing here is nobody talked to me about packaging.
I really dislike software instructing people to `make install` stuff left right and center and then not provide a way to uninstall.
And i understand them; I don't feel like writing code that removes stuff on peoples' systems either.

The solution is of course proper packaging - and as a hand-off point of what build artifacts are actually deliverables i guess make install is still the standard.

It was surprisingly hard to find any best-practices whatsoever...
Google's new AI engine just pigeon-holes any search to yield the most basic of Makefile results, and nothing more advanced, no matter the additional keywords used.
So it is just a simple cp for now.
