### ISSUE TITLE
Malformed page selection: pdf2printable -p 2-

### ISSUE THREAD

**Issue by milahu** [attah/ppm2pwg#29]
`pdf2printable` should allow open page ranges like `2-`
(meaning page 2 until the last page)

```
pdf2printable -f pwg -p 2- src.pdf dst.pwg
```

workaround: use `pdfinfo` to get the total page count

```
z=$(pdfinfo src.pdf | grep "^Pages:" | tail -c+18)
pdf2printable -f pwg -p 2-$z src.pdf dst.pwg
```

**Comment by attah** [comment]
You really have a way about you posting feature requests like if they were bug reports. Not very nice.

Pretty good suggestion none the less.
It isn't entirely trivial, as page ranges appear on IPP too and this is shared code. I'll see what i can do.

**Comment by attah** [comment]
Should be fixed by 1fe7d58

**Comment by milahu** [comment]
thanks

also handling open-starting ranges would be trivial
`-p -2` translates to `-p 1-2`

**Comment by attah** [comment]
Well, then i'd need to add special handling for that `-` is not valid in one way or another.
What would be the point of lower bound open? "1" is neither hard to type or hard to know.
